nelmio_api_doc:
    documentation:
        #        schemes: [http, https]
        info:
            title: English API
            description: Symfony JWT API docs
            version: 1.0.0
        securityDefinitions:
            Bearer:
                type: apiKey
                description: 'Authorization: Bearer {jwt}'
                name: Authorization
                in: header
        security:
            - Bearer: []
        tags:
            - name: "User"
              description: "User endpoints"
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/docs|/contexts|/{index}|/doc$) # Accepts routes under /api except